CREATE DATABASE IF NOT EXISTS TODO;
USE TODO;

CREATE USER IF NOT EXISTS 'ekipa'@'localhost' IDENTIFIED BY 'GesloZaEkipo123';
GRANT ALL PRIVILEGES ON TODO.* TO 'ekipa'@'localhost';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS Slike;
DROP TABLE IF EXISTS Zapis;

CREATE TABLE IF NOT EXISTS Zapis (
  ZapisID INT NOT NULL AUTO_INCREMENT,
  Zapis VARCHAR(100) NOT NULL,
  Opis VARCHAR(255) NOT NULL,
  Progress INT NOT NULL,	
  RokNaloge DATE,
  PRIMARY KEY (ZapisID)
  );
  
CREATE TABLE IF NOT EXISTS Slike (
  SlikeID  INT NOT NULL AUTO_INCREMENT,
  Slika LONGTEXT,
  ZapisTK INT,
  PRIMARY KEY (SlikeID),
  FOREIGN KEY (ZapisTK) REFERENCES Zapis(ZapisID)
  );