CREATE DATABASE IF NOT EXISTS TODO;
USE TODO;

CREATE USER 'ekipa'@'%' IDENTIFIED BY 'GesloZaEkipo123';
GRANT ALL PRIVILEGES ON TODO.* TO 'ekipa'@'%';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS Zapis;

CREATE TABLE IF NOT EXISTS Zapis (
  ZapisID INT NOT NULL AUTO_INCREMENT,
  Zapis VARCHAR(100) NOT NULL,
  Opis VARCHAR(255) NOT NULL,
  Progress INT NOT NULL,	
  PRIMARY KEY (ZapisID)
  );
  
  INSERT INTO Zapis(Zapis,Opis,Progress) VALUES ("ris", "naloga za ris", 10);

SELECT * FROM Zapis;
